### ISSUE TITLE
不登录无法查看问题详情及答案

### ISSUE THREAD

**Issue by Dev-Wiki** [answerdev/answer#100]
必现问题, 如图所示:
![image](https://user-images.githubusercontent.com/12946956/204431387-3389664c-4652-4a30-ad06-ad46a6fa73c8.png)

建议后台可以配置不登录可以查看问题详情和答案, 登录后可回答.

**Comment by Dev-Wiki** [comment]
这个比较严重, 这样基本等于不能使用了.

**Comment by aichy126** [comment]
This issue has been fixed, you can pull the latest image to fix it.

问题已经修复可以重新拉取最新的镜像

**Comment by Dev-Wiki** [comment]
好的 我拉一下

**Comment by Dev-Wiki** [comment]
已测试 最新版 0.4.2 不登录可以查看问题详情及答案
