### ISSUE TITLE
主题设置无论怎么选择都不会发生变换

### ISSUE THREAD

**Issue by Dev-Wiki** [answerdev/answer#102]
![image](https://user-images.githubusercontent.com/12946956/204437552-86ece049-26ad-42f5-a7dc-058ca4bd3fec.png)

如图所示, 怎么选择都是蓝色

**Comment by fenbox** [comment]
很抱歉这个功能还没开发好，不应该有 Light、Black 选项

**Comment by fenbox** [comment]
fixed in 1.0.0
