### ISSUE TITLE
请问是否该项目不允许或者不推荐使用中文反馈问题? 

### ISSUE THREAD

**Issue by Dev-Wiki** [answerdev/answer#108]
## 如果不允许或者不推荐使用中文反馈问题, 请在readme 中明确标记出, 而不是使用中文反馈以后, 因为是中文反馈而关闭 issue.

![image](https://user-images.githubusercontent.com/12946956/204950097-ca5da258-f848-497d-abf7-1ab5421274e7.png)

![image](https://user-images.githubusercontent.com/12946956/204950183-69bd82f1-ac04-46e9-999a-5562163fc51d.png)

![image](https://user-images.githubusercontent.com/12946956/204950266-236f21b8-4b45-4108-b21b-f96ebcfa11b6.png)

![image](https://user-images.githubusercontent.com/12946956/204950347-7d822976-79d8-4061-86ea-a9c1d4aa3972.png)

![image](https://user-images.githubusercontent.com/12946956/204950377-36d50c3d-8d92-4127-b0fa-60d099fc2018.png)

**Comment by Dev-Wiki** [comment]
@LinkinStars @shuashuai @aichy126 @robinv8

**Comment by joyqi** [comment]
Thanks for your advice. We've written a guide to help the members of our community to write good issues. You can find it here: #109 

We promote English only because we want to make sure that everyone can understand the issue. The left Chinese issues will be closed after fixing.
