### ISSUE TITLE
Is it possible to have an automatic front-end save for a question or answer being edited

### ISSUE THREAD

**Issue by hmlu** [answerdev/answer#117]
**Is your feature request related to a problem? Please describe.**

For example, if I am writing a question or answer, if I accidentally close the browser, refresh the browser or crash the computer, then the content I have written for half a day will be lost.

**Describe the solution you'd like**

Is it possible to make a timed automatic save to the LocalStorage of the user's browser, so that the content I wrote will not be lost even if the page is refreshed accidentally, or the machine crashes and other abnormal conditions.

Chineses Issue： #99

**Comment by fenbox** [comment]
Thank you for your suggestion, we'll add autosave to our plan.

**Comment by fenbox** [comment]
Released in version 1.0.6
