### ISSUE TITLE
Timezone cannot be saved

### ISSUE THREAD

**Issue by tmrwltd** [answerdev/answer#121]
**Describe the bug**
Changes to the time zone are not saved.

**To Reproduce**
1. Go to 'Admin > Settings > Interface'
2. Change Timezone (in my case) to 'Europe / Berlin'
3. Click on 'Save'
4. Nothing happens

**Expected behavior**
Time zone should have been changed to "Europe / Berlin".

**Platform (please complete the following information):**
 - Device: Desktop
 - OS: Windows 11
 - Browser Firefox
 - Version 108.0.1

**Comment by fenbox** [comment]
Fixed, please upgrade to v1.0.1
