### ISSUE TITLE
Plugin: OAuth login support

### ISSUE THREAD

**Issue by fenbox** [answerdev/answer#128]
Update: The OAuth plugin available here
https://github.com/answerdev/plugins

**Comment by amitsinghcode** [comment]
Login via Google and Apple account will be nice.

**Comment by jeesk** [comment]
github login

**Comment by soumendrak** [comment]
+1 for via Google login

**Comment by jozefrebjak** [comment]
Add login via Office365 please.

**Comment by mkubdev** [comment]
Using a custom SAML auth strategy could be cool too.

**Comment by diablowu** [comment]
Maybe gitlab should also be supported

**Comment by fenbox** [comment]
We just released a beta version about plugin and OAuth login, [have a try](https://github.com/answerdev/answer/releases/tag/v1.1.0-beta.1)
