### ISSUE TITLE
feature request for search multiple tags

### ISSUE THREAD

**Issue by erasewu** [answerdev/answer#136]
**Is your feature request related to a problem? Please describe.**
A question could be related with multiple tags at the same time, such as, "bug" + "productA", but at now, Answer can only filter one tag, it's not convenience for daily using. 

**Describe the solution you'd like**
If there any possible to add the search feature?

**Comment by fenbox** [comment]
You can filter multiple tags with search keywords such as `[bug] [productA]`. But the results has a bug, we'll fix it.

**Comment by fenbox** [comment]
Fixed, please upgrade to v1.0.1
