### ISSUE TITLE
MarkDown syntax problem of Bulleted List in the editor

### ISSUE THREAD

**Issue by jiangbonadia** [answerdev/answer#137]
**Describe the bug**
MarkDown syntax problem of Bulleted List in the editor.
I used the correct MarkDown syntax for Bulleted List, and the format is correct in the preview. But after published, the format goes wrong.

**Screenshots**
On the editing page:
![a833a1a9-7d9f-4e69-b288-3e13f69256b9](https://user-images.githubusercontent.com/1227386/208820847-c55c7313-6f2a-4c25-96f8-d311c8fcef0c.jpeg)
After published:
![0e683ebd-a66f-435a-9af2-991c43f920d4](https://user-images.githubusercontent.com/1227386/208820871-e00f49b1-a29e-4f32-b361-67168627cd17.jpeg)

**Comment by fenbox** [comment]
The editor preview was right, the published post was wrong.

**Comment by fenbox** [comment]
Fixed, please upgrade to v1.0.1
