### ISSUE TITLE
Suggest to add the tiltle when copy link on a question page

### ISSUE THREAD

**Issue by erasewu** [answerdev/answer#138]
**Is your feature request related to a problem? Please describe.**
When I before sharing a question to team, I would like to copy the link, but the `copy` function doesn't copy the question title, so I  need to add the question description again. 

**Describe the solution you'd like**
Click the `copy link` button, copy the question title and link at the same time.

**Comment by erasewu** [comment]
@fenbox 
Additional feature request:
Is it possible to change the sharelink in to shortlink?

**Comment by fenbox** [comment]
@erasewu You can create a new issue for this feature

**Comment by erasewu** [comment]
I create a new issue here.
[https://github.com/answerdev/answer/issues/139](https://github.com/answerdev/answer/issues/139)

**Comment by fenbox** [comment]
Fixed, please upgrade to v1.0.1
