### ISSUE TITLE
Search multiple tags with no results

### ISSUE THREAD

**Issue by erasewu** [answerdev/answer#142]
**Describe the bug**
Without keywords when searching using `[tag]` prompt, there's no results.
This is related with issue #136 .

**To Reproduce**
1. Go to 'Search'
2. Input '[tag]'
3. No results
4. Input '[tag]keywords'
5. Have results

**Expected behavior**
Can show all results without keywords when searching.

**Screenshots**
<img width="626" alt="image" src="https://user-images.githubusercontent.com/18375895/209427983-0fc498a3-9a1c-467c-a6f3-80f0c2bdf0d7.png">
<img width="607" alt="image" src="https://user-images.githubusercontent.com/18375895/209427988-54f0da15-86f4-42d4-a0f8-f332844c01ec.png">
<img width="694" alt="image" src="https://user-images.githubusercontent.com/18375895/209427992-6b1646d3-d002-4e32-84f3-0a71ec045084.png">
<img width="657" alt="image" src="https://user-images.githubusercontent.com/18375895/209427997-33e9eac6-a7c2-4d99-8c18-fdc599e99ac3.png">

**Platform (please complete the following information):**
 - Device: Desktop
 - OS: macOS
 - Browser: Chrome
 - Version: 1.0.1

**Comment by fenbox** [comment]
It looks like your question don't have the tag "bug".
You can see our demo [here](https://meta.answer.dev/search?q=%5Bbug%5D) and [there](https://meta.answer.dev/search?q=%5Bdiscussion%5D+%5Brules%5D).

**Comment by erasewu** [comment]
Hi @fenbox ,
I'm pretty sure the question have the tags.
screenshot attached below.
<img width="368" alt="image" src="https://user-images.githubusercontent.com/18375895/209431406-50ff916e-ff1b-4a41-852b-bfff1eb45860.png">

**Comment by erasewu** [comment]
I try to search `[bug][test]`
<img width="622" alt="image" src="https://user-images.githubusercontent.com/18375895/209431449-e834b89d-d8e8-4fff-ad2d-354d42f30cc5.png">

No result
<img width="625" alt="image" src="https://user-images.githubusercontent.com/18375895/209431458-2bc69e43-6433-4429-954b-f0dd0bb9721c.png">

but with a keyword `1224`, it works fine.
<img width="657" alt="image" src="https://user-images.githubusercontent.com/18375895/209431477-a43ed2a4-1056-467a-b97a-a241cd4714fa.png">

**Comment by kumfo** [comment]
Excuse me, are you sure your program version is 1.0.1? I can't reappear it in my local environment. I review the code of version 1.0.1, the fixed code is included.

https://github.com/answerdev/answer/commit/7e8906ebb1201455a18403654510f16f01d34da8

**Comment by erasewu** [comment]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/18375895/209915035-be3e862e-7544-496b-8bc8-4f87cdcefd91.png">
@kumfo sure it's 1.0.1, I'm using sqlite database for the testing.

**Comment by kumfo** [comment]
@erasewu Thank you, Maybe the sqlite not support this complex SQL query. I will try it now.

**Comment by erasewu** [comment]
With explicit keyword, it works fine.
Only without keyword, it has no result.

**Comment by kumfo** [comment]
It will be fixed in the next version, it's a sqlite query bug.

@erasewu

**Comment by erasewu** [comment]
thanks for the feedback, waiting for the next version.
