### ISSUE TITLE
🚩开一个 Answer 社区全数字化运营的讨论贴

### ISSUE THREAD

**Issue by will-ww** [answerdev/answer#15]
就像 @LinuxSuRen 在前面的 [Issue ](https://github.com/answerdev/answer/issues/3)中所提到的那样，可以考虑用一些数字化的工具来做一些社区运营的工作，特别是对于一个新项目来说，可以做各种尝试。

考虑到咱们以前也一起搞过 [opensource.win](https://opensource.win/) 的事情，不妨咱们就用这套来做 Answer 社区的数字化看板，目前这套方法也在我们实验室进行实验，@frank-zsy 也在其它社区做了些试点，效果挺好，能够量化贡献并激励大家往前冲~

我们甚至发起了一个[ XSOXI 计划](https://github.com/X-lab2017/open-wonderland/discussions/196)来促进社区的发展，根据贡献度给同学们发些助研的补助，效果不错~

如果有兴趣，我们可以联合 opensource.win 提供所有的数据支持和一些可视化的工具，一起来促进 Answer 社区的发展，基于此可以做的事情很多，也算是开源社区的社会实验了~

而且，等到下个月 Answer 社区的第一个月数据出来后，还可以用 [Hypercrx 插件](https://github.com/hypertrons/hypertrons-crx)对社区进行数据观测了，目前感觉社区热度在持续增加，非常期待，哈哈~

**Comment by Ritakang0451** [comment]
Mark~    为了提升人效比 一套好的工具，一个工具箱太有必要了。  打工多年， 大家一定都有各自的宝藏工具可以共享~

**Comment by joyqi** [comment]
Closed for non-English
