### ISSUE TITLE
Localization for 1.0.2 is still incomplete

### ISSUE THREAD

**Issue by Dev-Wiki** [answerdev/answer#157]
**the question detail page:**
![image](https://user-images.githubusercontent.com/12946956/210966672-52f853b3-c1e7-47a4-a7fa-ce224370c488.png)

![image](https://user-images.githubusercontent.com/12946956/210966730-8a9ca10b-9fee-427b-b05e-321a7824473f.png)

![image](https://user-images.githubusercontent.com/12946956/210966793-26b4b510-ee49-4726-9923-eff4c402e83d.png)

![image](https://user-images.githubusercontent.com/12946956/210966842-60b45550-bbe2-450b-b01b-598a1d4925d7.png)

**the users list page:**
![image](https://user-images.githubusercontent.com/12946956/210966975-af296b04-81f1-4631-a7a5-2c6beecb64c4.png)

**Comment by ungentilgarcon** [comment]
even more, it seems like localization is not taken into account, how to check it?


I'm trying to switch to french but it stays on english
