### ISSUE TITLE
Why are these files so big? Is it my installation problem?

### ISSUE THREAD

**Issue by beyondxuchao** [answerdev/answer#159]
![QQ图片20230106174221](https://user-images.githubusercontent.com/26999015/210974817-7ae217cc-d3a6-4603-82f6-547d80ec152b.jpg)

**Comment by haitaoo** [comment]
Analysis of the screenshot shows that the file was not gzipped during the transfer.

Can you provide some information about your browsing environment? 
For example, operating system, browser version, etc.
