### ISSUE TITLE
Is .gitlab-ci.yml still in use?

### ISSUE THREAD

**Issue by tisonkun** [answerdev/answer#16]
https://github.com/answerdev/answer/blob/main/.gitlab-ci.yml

It looks weird if we host this project on GitHub but keep such a config file.

**Comment by mingcheng** [comment]
This file is used by local developing envriment which was hosted by Gitlab. So, we remain this file and add it into git repository.

**Comment by tisonkun** [comment]
@mingcheng do you mean it's a non-issue? If so, we can close this issue as no planned.
