### ISSUE TITLE
Avatars in "/users" page will be squashed if a user uploaded an image which aspect ratio is not 1:1

### ISSUE THREAD

**Issue by realMorrisLiu** [answerdev/answer#164]
Avatars in "/users" page will be squashed if a user uploaded an image which aspect ratio is not 1:1.

For example, I uploaded an image which aspect ratio is 191x264
**To Reproduce**
1. Go to "/users/settings/profile"
2. Upload an image which aspect ratio is not 1:1, e.g. 191x264
3. Go to "/users"
4. You can see the avatar is squashed

**Expected behavior**
Avatar should not be squashed, just like the avatar displayed in navigation bar.

**Screenshots**
<img width="827" alt="image" src="https://user-images.githubusercontent.com/8832717/211268188-1e5352b5-c9df-4b04-a849-f88e5e047924.png">

**Platform (please complete the following information):**
 - Device: Desktop
 - OS: macOS
 - Browser: chrome
 - Version: 108

**Comment by realMorrisLiu** [comment]
I've made a pull request #165 to fix this issue.

**Comment by haitaoo** [comment]
> I've made a pull request #165 to fix this issue.
Thank you for your contribution!
PR #165 has been merged and it's time to close this issue.
