### ISSUE TITLE
How to use @mention in answers to tag someone for reply or response?

### ISSUE THREAD

**Issue by realMorrisLiu** [answerdev/answer#166]
Sometimes I want to use an "@" mark to mention someone to reply or request for an answer, but at this time, I don't  know how to do this with answer.dev.

**Comment by realMorrisLiu** [comment]
I've self hosted a service using image answerdev/answer:1.0.2, but the feature(@ mark) is not available. When I type "@" in comment, no candidate box visible.

**Comment by robinv8** [comment]
@realMorrisLiu This issue has been fixed in v1.0.3.
