### ISSUE TITLE
Most language have not been translated, but all of them show in language settings

### ISSUE THREAD

**Issue by fenbox** [answerdev/answer#170]
**Is your feature request related to a problem? Please describe.**

I chose language Deutsch and save, but the interface has not changed, which will cause me to know whether the translation is not completed or the settings are not effective. 

![image](https://user-images.githubusercontent.com/360618/211705732-85a6c20e-b127-4ff6-8b3b-6c09534f6155.png)

In face Deutsch is not translated. There are many language select options in Settings. But most of them have not been translated. I don't think it's good to show all of them.

**Describe the solution you'd like**

I think there need a translation progress, which will not be displayed if it is not reached 80%.

**Comment by HipyCas** [comment]
I was planning on working on the Spanish translation, and I found this in the docs: `If you would like to help us with the i18n translation, please visit [email protected]`. I guess the email protected shouldn't be there, so I'll follow the instructions above

**Comment by fenbox** [comment]
It's great that you'd like to help us translate. The tutorial is here #158.
We will fix the translation in the docs.

**Comment by haitaoo** [comment]
@HipyCas ok, you should now be able to access it normally. The previous text and the way you accessed it triggered the Cloudflare mail protection feature.

**Comment by HipyCas** [comment]
I've been contributing a bit to the Spanish translation, but it needs to be somehow approved to get in I believe, so how does it get into the codebase?

**Comment by fenbox** [comment]
@HipyCas Thank you. Our team members will approve. The translations will automatically be pulled into codebase.

**Comment by tmrwltd** [comment]
I already started with the German language version, but unfortunately got sick and had no time to continue.
Will try to finish it in the next days.

**Comment by fenbox** [comment]
We can see the progress of language translation in the settings now.
