### ISSUE TITLE
Comments can be edited when they are replied

### ISSUE THREAD

**Issue by leoyim** [answerdev/answer#177]
![image](https://user-images.githubusercontent.com/21982542/212888890-eb9f3a78-42e8-4239-8e0a-c35766bb85f9.png)
As shown above，when the first comment was replied, we can edited this comment.

I think that we can't edited the comment when it was replied, so I consider that should be added  limit when the comment or answers were replied，in order to ensure the credibility of information.

**Comment by fenbox** [comment]
We'v fixed it. Comment can be edited within 5 minutes after publish.
