### ISSUE TITLE
User bulk import

### ISSUE THREAD

**Issue by jbriard** [answerdev/answer#184]
**Is your feature request related to a problem? Please describe.**
I need to add a lot of users, and adding one by one is painfull

**Describe the solution you'd like**
Having the opportunity to import a list of user (only mails, or name + mails) directly in the admin console.
And then a temporary password is send by email.
During the user first connection, we force it to change it.

**Comment by fenbox** [comment]
Released in [v1.1.2](https://github.com/answerdev/answer/releases/tag/v1.1.2). You can bulk add users now.

But password email and force to change password not support yet.
