### ISSUE TITLE
 have any requirements for the browser version？

### ISSUE THREAD

**Issue by leozgn** [answerdev/answer#192]
I have deploy the project 1.0.4.
But when I use chrome version 83.0.4103.116 and firefox  68.12 ，I can not open the web，(The page displays the circle statu)
 when I use chrome v90 or upper, It can work.

so need to make any configuration，when use the lower version browser？

ths！

**Comment by shuashuai** [comment]
Thank you for your feedback. 
1. You can see the browser versions we support so far from /ui/README.md. 
![image](https://user-images.githubusercontent.com/30591202/217417656-cd7fa72a-3645-4243-ba94-f81508d8f87a.png)

2. In the future, we will add automatic prompts for unsupported browsers and inform users to upgrade their browsers to the corresponding version.
