### ISSUE TITLE
内部使用的时候遇到的一些问题和 Bug 修复「https://github.com/answerdev/answer/pull/191」

### ISSUE THREAD

**Issue by lcgash** [answerdev/answer#193]
首先非常感谢有这么好的一个开源项目供内部使用。但是在其中使用的时候发现或者遇到了一些问题，所以做了一些代码更改。

- 「feat」作为内部系统，需要告知大家应该在这里提交什么样的问题，那么一个类似于公告的东西是我们需要的。为了避免对代码的过多改造，支持了将问题置顶的功能，可以解决这个问题。
- 「fix」在取消点赞的时候，发现内部报错，后发现是一个关键字导致的。https://github.com/answerdev/answer/pull/195
- 「feat」作为内部系统，需要控制标签不那么杂乱，同时想设定能够管理员内置新增一些标签，所以支持了管理员在标签页增加标签的功能。
- 「fix」在使用标签同义词的时候，发现如果将 B 设置为 A 的同义词，那么之前绑定了 B 标签的问题将无法找到，通过索引 A 标签的方式。https://github.com/answerdev/answer/pull/196

见 PR：https://github.com/answerdev/answer/pull/191

**Comment by fenbox** [comment]
> 「fix」在使用标签同义词的时候，发现如果将 B 设置为 A 的同义词，那么之前绑定了 B 标签的问题将无法找到，通过索引 A 标签的方式。

确实标签 A 的问题列表应该包含标签 B 的问题

**Comment by lcgash** [comment]
> > 「fix」在使用标签同义词的时候，发现如果将 B 设置为 A 的同义词，那么之前绑定了 B 标签的问题将无法找到，通过索引 A 标签的方式。
> 
> 确实标签 A 的问题列表应该包含标签 B 的问题

我去把 pr 分开一下，上面的 pr 我先关闭掉

**Comment by zongyanshuo** [comment]
你搭建站点了吗兄弟  ，能留个联系方式不

**Comment by fenbox** [comment]
> 「feat」作为内部系统，需要控制标签不那么杂乱，同时想设定能够管理员内置新增一些标签，所以支持了管理员在标签页增加标签的功能。

很抱歉这个 feature 涉及的内容比较多，为了保持一致性以及其他 tag 相关的权限调整，我们无法合并这个 feature。
为了弥补不足，我们在 1.0.7 版本增加了 `/tags` 页面创建标签的功能，希望你能用上。

感谢你的贡献，我们也即将开放插件功能，以此来扩充功能，希望你能继续关注。
