### ISSUE TITLE
footer section

### ISSUE THREAD

**Issue by thesorskod** [answerdev/answer#221]
**Describe the bug**
modifying/making changes to the 'en_US.yaml' file. doe not update the footer section.

```
  footer:
    build_on: >-
      Built on <1> Answer </1>- the open-source software that powers Q&A
      communities.<br />Made with love © {{cc}}.
```

answer > i18n > en_US.yaml > line 585

**To Reproduce**
1. Go to 'answer > 118n > en_US.yaml > line 585'
2. modify footer text 'line 585'

```
  footer:
    build_on: >-
      Built on <1> Answer </1>- the open-source software that powers Q&A
      communities.<br />Made with love © {{cc}}.
```

4. Save file.

**Expected behavior**
changes made to the file update footer section on all pages.

**Comment by thesorskod** [comment]
> 1. For production environment，after the modification is complete, have you re-packaged and deployed?
> 2. For development environment, if you changed this file, you should be able to see the modified copy directly!
> 
> If neither of the above two is true, please continue to give feedback

In productions/dev

log show-
[i18n] install en_US.yaml bundle success \
[i18n] install es_ES.yaml file exist, try to replace it \
[i18n] install es_ES.yaml bundle... \
[i18n] install es_ES.yaml bundle success

**Comment by shuashuai** [comment]
Did you recompile after editing？After you edit the language file, first you should compile it, then use docker build to package the image, and finally start the above packaged image.
