### ISSUE TITLE
没有seo，没有邮件配置

### ISSUE THREAD

**Issue by RayPragma** [answerdev/answer#23]
新人，想问下
没有seo，没有邮件配置

**Comment by geekymv** [comment]
> 新人，想问下 没有seo，没有邮件配置

看其他 issue，SEO 相关正在开发中 #9 
邮件配置，使用默认的 admin@admin.com / admin 帐号登录，可以看到 Admin 菜单，Settings -> 配置 SMTP

**Comment by fenbox** [comment]
SEO 已支持
