### ISSUE TITLE
如何构建dev环境

### ISSUE THREAD

**Issue by dgodance** [answerdev/answer#24]
如何构建dev环境

**Comment by geekymv** [comment]
> 如何构建dev环境

@sunful 可以参考 [快速搭建 SegmentFault思否开源的问答社区软件 Answer](https://segmentfault.com/a/1190000042687328)

**Comment by sunful** [comment]
> > 如何构建dev环境
> 
> @sunful 可以参考 [快速搭建 SegmentFault思否开源的问答社区软件 Answer](https://segmentfault.com/a/1190000042687328)

前端可以实时编译吗

**Comment by RayPragma** [comment]
以后会不会有多端，微信登录

**Comment by geekymv** [comment]
> > > 如何构建dev环境
> > 
> > 
> > @sunful 可以参考 [快速搭建 SegmentFault思否开源的问答社区软件 Answer](https://segmentfault.com/a/1190000042687328)
> 
> 前端可以实时编译吗

可以实时编译的，参考文档 [ui/README.md](https://github.com/answerdev/answer/blob/main/ui/README.md) 和 #33
