### ISSUE TITLE
Need permission configure to delete answer

### ISSUE THREAD

**Issue by coanor** [answerdev/answer#244]
**Is your feature request related to a problem? Please describe.**
While some abuse answers among questions, the admin need to delete them, all delete click throw "No permission to delete". And I can't find such configure to enable the deletion.

**Describe the solution you'd like**
Enable high-permission user to delete any answer questions.

**Comment by shuashuai** [comment]
Currently in answer system, administrators and moderator and authors have permission to delete. you can add admin privileges to a user from the path below.

-> /admin -> /admin/users

![image](https://user-images.githubusercontent.com/30591202/223315147-f23c5262-3cdd-4ea8-b1b0-f5b8dd749a88.png)

then click action
![image](https://user-images.githubusercontent.com/30591202/223315243-92a59c5e-80ff-4870-86da-795c625b904f.png)

![image](https://user-images.githubusercontent.com/30591202/223315518-39ed75a9-1668-4860-9877-cce45c5fae4d.png)

By following the steps above, you can change the permissions of some users in the system. Of course only administrators can enter /admin, so please log in with an administrator account to complete the above wipe.

**Comment by coanor** [comment]
The thread I answered myself can not delete?

**Comment by shuashuai** [comment]
What is the role of your current login account? Does your login account have access to /admin? If you can access /admin normally, then your current logged-in user is already an administrator and can delete any content.If it is just an ordinary user, then he can only delete the content written by himself.

You just need to set the administrator role for the users who need administrative rights.
