### ISSUE TITLE
the code block Display Error when edit question content and answer on version 1.0.7

### ISSUE THREAD

**Issue by Dev-Wiki** [answerdev/answer#275]
the question page: https://qa.devwiki.net/questions/D1g2/ru-he-zai-windows11shang-qi-dong-ieliu-lan-qi

![image](https://user-images.githubusercontent.com/12946956/227136153-262820ba-ff70-484c-ab96-92e358e784d9.png)

![image](https://user-images.githubusercontent.com/12946956/227136331-ebfbe572-6daf-4dcf-8439-e0433fe5329a.png)

**Comment by aichy126** [comment]
markdown rendering issue was hotfixed in 1.0.7
Can you download the latest version and try it again?

**Comment by Dev-Wiki** [comment]
> markdown rendering issue was hotfixed in 1.0.7 Can you download the latest version and try it again?

就是 1.0.7 版本

**Comment by Dev-Wiki** [comment]
![image](https://user-images.githubusercontent.com/12946956/227165143-0fd7a70b-79e4-464c-8192-f8d393abcc15.png)

**Comment by aichy126** [comment]
Yes we have a fix for 1.0.7, I wonder if you used the package before the fix

**Comment by Dev-Wiki** [comment]
> Yes we have a fix for 1.0.7, I wonder if you used the package before the fix

我是从1.0.6 升级到 1.0.7 的

**Comment by Dev-Wiki** [comment]
git如何在本地更新远程分支列表? - DevWiki Q&A
https://qa.devwiki.net/questions/D1D1/gitru-he-zai-ben-di-geng-xin-yuan-cheng-fen-zhi-lie-biao

这个页面是老版本时候创建的问题, 看起来显示还算正常.

**Comment by aichy126** [comment]
If it is a docker deployment you can pull the following latest images.
If it is a binary deployment, you can also download the latest file.
1.0.7 there have been two submissions, and you are likely to download previous submissions
https://github.com/answerdev/answer/compare/v1.0.7...main

**Comment by aichy126** [comment]
> git如何在本地更新远程分支列表? - DevWiki Q&A https://qa.devwiki.net/questions/D1D1/gitru-he-zai-ben-di-geng-xin-yuan-cheng-fen-zhi-lie-biao
> 
> 这个页面是老版本时候创建的问题, 看起来显示还算正常.

We just checked the docker file and binary file of v1.0.7 and found that the binary file was not updated. We will deal with this problem

**Comment by aichy126** [comment]
> > Yes we have a fix for 1.0.7, I wonder if you used the package before the fix
> 
> 我是从1.0.6 升级到 1.0.7 的

https://github.com/answerdev/answer/releases/tag/v1.0.7
We reuploaded the binary file 
Thank you for your feedback.

**Comment by Dev-Wiki** [comment]
> > > Yes we have a fix for 1.0.7, I wonder if you used the package before the fix
> > 
> > 
> > 我是从1.0.6 升级到 1.0.7 的
> 
> https://github.com/answerdev/answer/releases/tag/v1.0.7 We reuploaded the binary file Thank you for your feedback.

docker 镜像没有更新
https://hub.docker.com/r/answerdev/answer

**Comment by aichy126** [comment]
> > > > Yes we have a fix for 1.0.7, I wonder if you used the package before the fix
> > > 
> > > 
> > > 我是从1.0.6 升级到 1.0.7 的
> > 
> > 
> > https://github.com/answerdev/answer/releases/tag/v1.0.7 We reuploaded the binary file Thank you for your feedback.
> 
> docker 镜像没有更新 https://hub.docker.com/r/answerdev/answer

You can just use the latest image and this is always up to date.
We will create an action to fix the image of 1.0.7.

**Comment by Dev-Wiki** [comment]
> 

这是我的docker部署:
```yml
version: '3'

services:
  answer:
    image: answerdev/answer:latest
    restart: always
    ports:
      - '9082:80'
    volumes:
      - ./data:/data
```

然后这是我拉去的镜像, md 显示代码的问题仍然存在, 目前看来 仍旧没有更新. 

![image](https://user-images.githubusercontent.com/12946956/227407169-27fc3447-f859-422c-822c-0516063bd035.png)

**Comment by Dev-Wiki** [comment]
重新编辑问题后 显示正常了.

**Comment by fenbox** [comment]
@Dev-Wiki 核心代码暂不支持代码高亮，你可以开发个插件，这样大家都能用 ^__^
