### ISSUE TITLE
Elasticsearch is a good candidate for the underlying database?

### ISSUE THREAD

**Issue by marshell0** [answerdev/answer#29]
For Q/A, is ES a better solution for this? I think it will simplify the development and improve the performance
Do you have any plan for supporting ES in you roadmap?

**Comment by loid345** [comment]
Meilisearch better 
https://github.com/meilisearch/meilisearch-go

**Comment by joyqi** [comment]
Interesting idea. ElasticSearch is good for searching, but for storing data, it's still debatable.

In Answer project, we use XORM to be the abstraction layer of database, so all data operations are designed for relational database. If you want to use ElasticSearch, you need to write your own data access layer. We'll continue to discuss this issue, and add ES support in our roadmap if it's necessary.

**Comment by ppchart** [comment]
It may be possible to use ES only for storage and search of critical data, such as titles and question content

**Comment by fenbox** [comment]
Answer will support third-party search engine such as Elasticsearch plugin.
