### ISSUE TITLE
The markdown table in the answer content is displayed abnormally on 1.0.7

### ISSUE THREAD

**Issue by Dev-Wiki** [answerdev/answer#291]
version : 1.0.7

page: Windows系统有哪些快捷访问系统目录的方式? - DevWiki Q&A
https://qa.devwiki.net/questions/D1p2/windowsxi-tong-you-na-xie-kuai-jie-fang-wen-xi-tong-mu-lu-de-fang-shi/E1q2

when editing: 

![image](https://user-images.githubusercontent.com/12946956/228119594-b2d958ba-3d37-43c9-a49d-8efb3a95b225.png)

submit:

![image](https://user-images.githubusercontent.com/12946956/228119769-48f4bb35-b18a-46e9-825e-4f4190c6535c.png)

**Comment by shuashuai** [comment]
Thanks for your feedback, we will fix this bug in 1.0.8.

**Comment by Dev-Wiki** [comment]
测试 1.0.8 显示正常
![image](https://user-images.githubusercontent.com/12946956/231134486-ad34eaa1-f068-4d55-ad83-42ece5e2adaf.png)
