### ISSUE TITLE
Code highlight support in markdown

### ISSUE THREAD

**Issue by YuJianghao** [answerdev/answer#298]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when code highlight is not available.

![image](https://user-images.githubusercontent.com/17293034/229420965-51166643-7d60-4206-a226-8d47afd9bc5d.png)

**Describe the solution you'd like**
Add the support. Like what Github do.

```js
app.use((err, req, res, next) => {
  console.error(err.stack)
  res.status(500).send('Something broke!')
})
```

**Describe alternatives you've considered**
N/A

**Comment by shuashuai** [comment]
In our product ecology, we want this feature to be implemented by the plugin system, so this feature is not in our release planning.

**Comment by shuashuai** [comment]
Until our plugin system supports it, it does. Unless you can do secondary development.
