### ISSUE TITLE
可否在github的项目首页交换友情链接？

### ISSUE THREAD

**Issue by shishirui** [answerdev/answer#30]
我们的项目是：
https://github.com/PGYER/codefever

盼复

**Comment by jiangbonadia** [comment]
Hi 我们讨论了一下，决定暂时还是不要在 GitHub 主页上添加和项目无关的内容，不过欢迎联系我（wechat：nadia61），我们可以考虑之后联合做一些开发者活动

Hi, We've discussed about that but finally decided not to add anything unrelated to the project on the homepage. But feel free to contact me (WeChat: nadia61) ,maybe we can discuss doing some developer events together in the future.
