### ISSUE TITLE
Some translations do not work

### ISSUE THREAD

**Issue by BingYanchi** [answerdev/answer#309]
![image](https://user-images.githubusercontent.com/36477925/230728904-f5255ce1-e8cc-4bb5-a1bf-f3eb05093804.png)
![image](https://user-images.githubusercontent.com/36477925/230728825-62b21231-5ada-410e-9a22-a486b799b618.png)
![image](https://user-images.githubusercontent.com/36477925/230728850-6bf605de-7678-4f80-8786-60da0dce17e2.png)

Some translations didn't work, they were focused on the question's action options.

**Comment by BingYanchi** [comment]
I found that the localization file contains mail related content, but it didn't take effect. It seems that it saves the format directly into the database when setting up SMTP, and it is only in English. Localized text is not selected according to the language of the site, nor according to the language of the user being sent.

**Comment by BingYanchi** [comment]
![image](https://user-images.githubusercontent.com/36477925/230816531-78feb0db-2045-40ac-b694-82c18f2a79f9.png)
The type in timeline does not seem to use the content in backend.timeline correctly, but selects the content in backend.question_detail.

**Comment by shuashuai** [comment]
> ![image](https://user-images.githubusercontent.com/36477925/230816531-78feb0db-2045-40ac-b694-82c18f2a79f9.png) The type in timeline does not seem to use the content in `backend.timeline` correctly, but selects the content in `backend.question_detail`.

I don't understand exactly what you mean by the problem you describe. Our history feature is only for questions, answers, tags, and actions that generate versions to add records, so there is no problem with types here.

**Comment by BingYanchi** [comment]
> > ![image](https://user-images.githubusercontent.com/36477925/230816531-78feb0db-2045-40ac-b694-82c18f2a79f9.png) The type in timeline does not seem to use the content in `backend.timeline` correctly, but selects the content in `backend.question_detail`.
> 
> I don't understand exactly what you mean by the problem you describe. Our history feature is only for questions, answers, tags, and actions that generate versions to add records, so there is no problem with types here.
> 

I tried to change the backend.timeline in i18n. In theory, he should modify the content in the "类型" of this page. Because the context of "提交于" should not appear in the form.

In the Chinese context. "提交于" should be connected to time. But here is a table. There is no direct connection to time. So I tried to change it to "提交". But it failed. Maybe it used backend.question_detail

**Comment by BingYanchi** [comment]
> > ![image](https://user-images.githubusercontent.com/36477925/230816531-78feb0db-2045-40ac-b694-82c18f2a79f9.png) The type in timeline does not seem to use the content in `backend.timeline` correctly, but selects the content in `backend.question_detail`.
> 
> @BingYanchi Can you describe the problem in a little more detail? We don't quite understand what you mean by `backend.timeline` and `backend.question_detail`.

Maybe I didn't express it clearly enough. I was referring to the yaml path in i18n.

**Comment by shuashuai** [comment]
> > > ![image](https://user-images.githubusercontent.com/36477925/230816531-78feb0db-2045-40ac-b694-82c18f2a79f9.png) The type in timeline does not seem to use the content in `backend.timeline` correctly, but selects the content in `backend.question_detail`.
> > 
> > 
> > I don't understand exactly what you mean by the problem you describe. Our history feature is only for questions, answers, tags, and actions that generate versions to add records, so there is no problem with types here.
> 
> I tried to change the backend.timeline in i18n. In theory, he should modify the content in the "类型" of this page. Because the context of "提交于" should not appear in the form.
> 
> In the Chinese context. "提交于" should be connected to time. But here is a table. There is no direct connection to time. So I tried to change it to "提交". But it failed. Maybe it used backend.question_detail
> 
> I tried to directly modify the local i18n file. And restart the site. But it still didn't take effect.


You should change the content in ui.timeline. The backend is the translation content applied to the backend, and the content below the ui is the translation content applied to the frontend.

**Comment by BingYanchi** [comment]
> > > > ![image](https://user-images.githubusercontent.com/36477925/230816531-78feb0db-2045-40ac-b694-82c18f2a79f9.png) The type in timeline does not seem to use the content in `backend.timeline` correctly, but selects the content in `backend.question_detail`.
> > > 
> > > 
> > > I don't understand exactly what you mean by the problem you describe. Our history feature is only for questions, answers, tags, and actions that generate versions to add records, so there is no problem with types here.
> > 
> > I tried to change the backend.timeline in i18n. In theory, he should modify the content in the "类型" of this page. Because the context of "提交于" should not appear in the form.
> > 
> > In the Chinese context. "提交于" should be connected to time. But here is a table. There is no direct connection to time. So I tried to change it to "提交". But it failed. Maybe it used backend.question_detail
> > 
> > I tried to directly modify the local i18n file. And restart the site. But it still didn't take effect.
> 
> 
> You should change the content in ui.timeline. The backend is the translation content applied to the backend, and the content below the ui is the translation content applied to the frontend.Our language file is based on the en_US.yaml file, you can see
> 
> ![image](https://user-images.githubusercontent.com/30591202/230839702-a617ba42-c28f-4447-957e-495854b537c1.png)
> 

Sorry. My description is wrong. What I modified is ui.timeline. But it still doesn’t take effect.

**Comment by shuashuai** [comment]
For the development environment, the edits will be logged to take effect after they are done, for the production environment after the edits are done, you need to repackage and deploy the code for it to take effect.

**Comment by BingYanchi** [comment]
> <img alt="image" width="359" src="https://user-images.githubusercontent.com/19712692/231338899-f0f35a73-f4ee-446c-84c9-c743c564b319.png">
> 
> We just did not find this problem after using the Chinese for test. You can check if it is caused by browser cache. Version is (answerdev/answer:1.0.8)

I've tried clearing my browser cache, even on a computer that never visits the site, same thing.

There should be other reasons.

**Comment by BingYanchi** [comment]
> FYI:
> 
> 1. Follow the steps in the documentation to upgrade correctly https://answer.dev/docs/upgrade
> 2. Make sure the `data/i18n/en_US.yaml` language file is the same as the latest language file on github
> 3. make sure that the en_US.yaml file contains the key `backend.action.report` etc.
>    Also, may I ask, which way are you using to deploy, docker or binary?

The problem is solved, I am using binary, and it is normal after I manually update the i18n file.

**Comment by BingYanchi** [comment]
In 1.0.9, the reason selection in the close and report popups still doesn't take effect. Type filtering in report management is also not localized properly.
![image](https://user-images.githubusercontent.com/36477925/234731099-827d5322-0697-4bb3-8228-26fe5fd3d296.png)

**Comment by BingYanchi** [comment]
In 1.1.0-beta.2, the reason selection in the close and report popups still doesn't take effect.

**Comment by BingYanchi** [comment]
Done in v1.1.0, thanks
