### ISSUE TITLE
500 Error when trying to view profiles

### ISSUE THREAD

**Issue by cl-christschantz** [answerdev/answer#321]
**Describe the bug**
When viewing your own profile or any other users profile, you receive a 500 error.
https://fqdn/users/XXXXX

**To Reproduce**
1. Go to Users
2. Click on any user profile

Any location at http(s)://fqdn/users/xxxxxx

**Expected behavior**
The User profiles display without a 500 error page.

**Screenshots**
Exact Error in the logs:
```
2023-04-12 20:11:43.874	ERROR	/go/src/github.com/answerdev/answer/internal/base/handler/handler.go:36	code: 500, reason: base.database_error, message: , error: pq: invalid input syntax for type bigint: ""
/go/src/github.com/answerdev/answer/internal/repo/answer/answer_repo.go:252 github.com/answerdev/answer/internal/repo/answer.(*answerRepo).SearchList
/go/src/github.com/answerdev/answer/internal/service/answer_common/answer.go:54 github.com/answerdev/answer/internal/service/answer_common.(*AnswerCommon).Search
/go/src/github.com/answerdev/answer/internal/service/question_service.go:817 github.com/answerdev/answer/internal/service.(*QuestionService).SearchUserTopList
/go/src/github.com/answerdev/answer/internal/controller/question_controller.go:499 github.com/answerdev/answer/internal/controller.(*QuestionController).UserTop
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 github.com/gin-gonic/gin.(*Context).Next
/go/src/github.com/answerdev/answer/internal/base/middleware/auth.go:66 github.com/answerdev/answer/internal/base/middleware.(*AuthUserMiddleware).EjectUserBySiteInfo.func1
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 github.com/gin-gonic/gin.(*Context).Next
/go/src/github.com/answerdev/answer/internal/base/middleware/auth.go:53 github.com/answerdev/answer/internal/base/middleware.(*AuthUserMiddleware).Auth.func1
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/anargu/gin-brotli@v0.0.0-20220116052358-12bf532d5267/gin_brotli.go:71 github.com/anargu/gin-brotli.Brotli.func1
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 github.com/gin-gonic/gin.(*Context).Next
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616 github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572 github.com/gin-gonic/gin.(*Engine).ServeHTTP
/usr/local/go/src/net/http/server.go:2947 net/http.serverHandler.ServeHTTP
/usr/local/go/src/net/http/server.go:1991 net/http.(*conn).serve
/usr/local/go/src/runtime/asm_amd64.s:1594 runtime.goexit
```

**Platform:**
 - Device: Desktop
 - OS: macOS
 - Browser Chrome
 - Version 1.0.8
 - Database Type: Postgres (GCP Cloud SQL)
 - Database Version: 14

**Comment by aichy126** [comment]
Can you provide an accessible web address, or provide more detailed information, such as whether the user answered or asked questions.
We have temporarily repeated this error

**Comment by cl-christschantz** [comment]
This happens for all users regardless on if they have asked, answered or both asked and answered questions.

Additionally, this appears to occur when clicking on a question when not logged in.

**Comment by lostmaniac** [comment]
根据你提供的错误日志，看起来是在使用 PostgreSQL 数据库时出现了一个问题。具体来说，这个错误是由于尝试将一个空字符串转换为 bigint 类型所引起的。这通常表示在数据库中的某个地方，一个期望是非空 bigint 类型的列或变量，实际上包含了一个空字符串。

为了解决这个问题，你可以检查你的代码，查看是否有任何尝试将空字符串赋值给 bigint 类型的操作。如果是这种情况，请确保在将值插入数据库之前先检查它是否为空。

另外，你还可以检查数据库中的表结构，确保所有 bigint 列都被定义为非空类型。如果存在空字符串的情况，你可以考虑将这些列的默认值更改为适当的非空值，或者在插入数据时显式指定这些列的值。

最后，如果你仍然无法解决问题，你可能需要进一步调查错误日志中提供的堆栈跟踪，以找到导致该错误的具体代码行。

**Comment by aichy126** [comment]
We will fix this problem in the next version. Thank you for your feedback.
https://github.com/answerdev/answer/issues/336
