### ISSUE TITLE
pgsql compatibility issue

### ISSUE THREAD

**Issue by lostmaniac** [answerdev/answer#328]
answerdev error：/go/src/github.com/answerdev/answer/internal/base/handler/handler.go:36	code: 500, reason: base.database_error, message: , error: pq: invalid input syntax for type bigint: ""

postgrsql error：
pgsql     | 2023-04-19 06:27:46.491 UTC [1] LOG:  database system is ready to accept connections
pgsql     | 2023-04-19 06:29:32.393 UTC [37] ERROR:  invalid input syntax for type bigint: ""
pgsql     | 2023-04-19 06:29:32.393 UTC [37] CONTEXT:  unnamed portal parameter $3 = ''
pgsql     | 2023-04-19 06:29:32.393 UTC [37] STATEMENT:  SELECT "id", "created_at", "updated_at", "question_id", "user_id", "last_edit_user_id", "original_text", "parsed_text", "status", "adopted", "comment_count", "vote_count", "revision_id" FROM "answer" WHERE (user_id = $1) AND (status = $2 OR user_id = $3) ORDER BY vote_count desc LIMIT 5
pgsql     | 2023-04-19 06:29:36.672 UTC [36] ERROR:  invalid input syntax for type bigint: ""
pgsql     | 2023-04-19 06:29:36.672 UTC [36] CONTEXT:  unnamed portal parameter $3 = ''
pgsql     | 2023-04-19 06:29:36.672 UTC [36] STATEMENT:  SELECT "id", "created_at", "updated_at", "question_id", "user_id", "last_edit_user_id", "original_text", "parsed_text", "status", "adopted", "comment_count", "vote_count", "revision_id" FROM "answer" WHERE (user_id = $1) AND (status = $2 OR user_id = $3) ORDER BY vote_count desc LIMIT 5
pgsql     | 2023-04-19 06:29:43.908 UTC [37] ERROR:  invalid input syntax for type bigint: ""
pgsql     | 2023-04-19 06:29:43.908 UTC [37] CONTEXT:  unnamed portal parameter $3 = ''
pgsql     | 2023-04-19 06:29:43.908 UTC [37] STATEMENT:  SELECT "id", "created_at", "updated_at", "question_id", "user_id", "last_edit_user_id", "original_text", "parsed_text", "status", "adopted", "comment_count", "vote_count", "revision_id" FROM "answer" WHERE (user_id = $1) AND (status = $2 OR user_id = $3) ORDER BY vote_count desc LIMIT 5
pgsql     | 2023-04-19 06:29:56.708 UTC [37] ERROR:  invalid input syntax for type bigint: ""
pgsql     | 2023-04-19 06:29:56.708 UTC [37] CONTEXT:  unnamed portal parameter $3 = ''
pgsql     | 2023-04-19 06:29:56.708 UTC [37] STATEMENT:  SELECT "id", "created_at", "updated_at", "question_id", "user_id", "last_edit_user_id", "original_text", "parsed_text", "status", "adopted", "comment_count", "vote_count", "revision_id" FROM "answer" WHERE (user_id = $1) AND (status = $2 OR user_id = $3) ORDER BY vote_count desc LIMIT 5
pgsql     | 2023-04-19 06:32:28.209 UTC [37] ERROR:  duplicate key value violates unique constraint "user_pkey"
pgsql     | 2023-04-19 06:32:28.209 UTC [37] DETAIL:  Key (id)=(1) already exists.
pgsql     | 2023-04-19 06:32:28.209 UTC [37] STATEMENT:  INSERT INTO "user" ("created_at","updated_at","suspended_at","deleted_at","last_login_date","username","pass","e_mail","mail_status","notice_status","follow_count","answer_count","question_count","rank","status","authority_group","display_name","avatar","mobile","bio","bio_html","website","location","ip_info","is_admin","language") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26) RETURNING "id"
pgsql     | 2023-04-19 06:32:42.781 UTC [36] ERROR:  invalid input syntax for type bigint: ""

Based on the error logs provided, it appears that there is an issue with the PostgreSQL database in relation to input syntax for a bigint type. Additionally, there is a duplicate key value violation error, which suggests that there may be an attempt to insert a record with a key that already exists.

To report this issue, you can use the following issue template:

Describe the bug
There seems to be an issue with the PostgreSQL database related to input syntax for a bigint type, as well as a duplicate key value violation error.

To Reproduce

Attempt to insert a record with a key that already exists.
Perform a query using a bigint type.
Note the resulting errors in the log.
Expected behavior
There should be no errors related to input syntax or duplicate key value violations.

Screenshots
N/A

Platform

PostgreSQL version: 15.2
CPU：ARM
Operating system:  debian/docker
Relevant application and version: 1.0.8

**Comment by lostmaniac** [comment]
looking users in the foreground and adding users in the background will result in errors.

**Comment by lostmaniac** [comment]
我大概找到问题了，文档里，
display_name
avatar
mobile
bio
bio_html
website
location
可以为空，但是实际数据库设计时候，不能为空，mysql这样用没问题，pgsql这样就会报错。

**Comment by aichy126** [comment]
We will fix this problem in the next version. Thank you for your feedback.
#336
