### ISSUE TITLE
Page request timeout

### ISSUE THREAD

**Issue by geekymv** [answerdev/answer#33]
- ui start success, but request timeout

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/4549602/198261419-33d6ffef-3b3f-4356-a5ed-c9ccba1f7647.png">

- backend 
<img width="726" alt="image" src="https://user-images.githubusercontent.com/4549602/198262472-93ca9a94-aa3f-4ed8-9404-53f0766ed8c7.png">

**Comment by shuashuai** [comment]
You only need to configure the proxy to the address of your service，then restart ui。
（ui/config-overrides.js）
![image](https://user-images.githubusercontent.com/30591202/198450642-97176fbc-3f4b-43e4-85bc-b2cf91ebd870.png)

**Comment by shuashuai** [comment]
First make sure your go service starts, then you just need to change the proxy option in ui/config-overfides.js to your local service address. Then restart it. In the next release we will provide configuration files for local development.

![image](https://user-images.githubusercontent.com/30591202/198465316-071bf6b5-2052-4e84-9423-a557d6fa5e62.png)

**Comment by geekymv** [comment]
> First make sure your go service starts, then you just need to change the proxy option in ui/config-overfides.js to your local service address. Then restart it. In the next release we will provide configuration files for local development.
> 
> ![image](https://user-images.githubusercontent.com/30591202/198465316-071bf6b5-2052-4e84-9423-a557d6fa5e62.png)

i see, thank you
