### ISSUE TITLE
Cannot open user details

### ISSUE THREAD

**Issue by frafra** [answerdev/answer#336]
**Describe the bug**
Clicking on a user raises a server error.

**To Reproduce**
1. Go to Users
2. Click on a user
3. See error HTTP 50X

Server logs:
```
ERROR	/go/src/github.com/answerdev/answer/answer_build3060150450/vendor/github.com/answerdev/answer/internal/base/handler/handler.go:36	code: 500, reason: base.database_error, message: , error: pq: invalid input syntax for type bigint: ""
```

Database logs:
```
,
PostgreSQL Database directory appears to contain a database; Skipping initialization,
,
[34] ERROR:  invalid input syntax for type bigint: "",
[34] CONTEXT:  unnamed portal parameter $3 = '',
[34] STATEMENT:  SELECT "id", "created_at", "updated_at", "question_id", "user_id", "last_edit_user_id", "original_text", "parsed_text", "status", "adopted", "comment_count", "vote_count", "revision_id" FROM "answer" WHERE (user_id = $1) AND (status = $2 OR user_id = $3) ORDER BY vote_count desc LIMIT 5,
```

It looks like `user_id` is empty.

Reply to browser request `GET http://localhost/answer/api/v1/personal/qa/top?username=admin`:
```json
{"code":500,"reason":"base.database_error","msg":"Data server error.","data":{"answer":[],"question":[]}}
```

**Expected behavior**
See user details.

**Screenshots**

Not a screenshot, but it is pretty close to it :)
```
(=‘x‘=)
HTTP Error 50X
The server encountered an error and could not complete your request.
```

**Platform (please complete the following information):**
Docker image, 1.1.0, Postgres database, OAuth2 plugin enabled.

**Comment by frafra** [comment]
The problem only happens when using Postgres. SQLite and MySQL are not affected. SQLite does not enforce type checks:

Sqlite:
```
sqlite> select * from answer where user_id = '';
sqlite> 
```

MySQL:
```
mysql> select * from answer where user_id = '';
Empty set (0.00 sec)
```

This is because an empty string is casted to `0` in both databases, thus hiding the coding error.
Postgres fails:

Postgres:
```
answer=# select * from answer where user_id = '';
ERROR:  invalid input syntax for type bigint: ""
LINE 1: select * from answer where user_id = '';
```

**Comment by frafra** [comment]
The problem seems to came from here:

https://github.com/answerdev/answer/blob/6695200b65335b360a100fa73cb0c3d96b974592/internal/controller/question_controller.go#L544C12-L553

https://github.com/answerdev/answer/blob/6695200b65335b360a100fa73cb0c3d96b974592/internal/base/middleware/auth.go#L144-L150

So, returning an empty string when the value is `nil`, equals to returning `0`. This would include results of a user with id 0 potentially. Why do not return `nil` as it is, so that it gets cast to `NULL`? No corner case scenarios, no incompatibilities between databases.

**Comment by cl-christschantz** [comment]
Lots of detail posted by frafra. Fixing this should also close the following issues:

https://github.com/answerdev/answer/issues/321
https://github.com/answerdev/answer/issues/328

**Comment by rom8726** [comment]
Bug is here: https://github.com/answerdev/answer/blob/main/internal/repo/answer/answer_repo.go#L246
There is should be search.UserID as second parameter.

@frafra No, problem not in GetLoginUserIDFromContext(), you should pass Authorization token.

**Comment by aichy126** [comment]
> Bug is here: https://github.com/answerdev/answer/blob/main/internal/repo/answer/answer_repo.go#L246 There should be search.UserID as second parameter.
> 
> @frafra No, problem not in GetLoginUserIDFromContext(), you should pass Authorization token.

Thanks for the feedback. Postgres does have problems. We will fix this issue in the latest version
