### ISSUE TITLE
Users' profile shows downvotes that do not exist

### ISSUE THREAD

**Issue by frafra** [answerdev/answer#352]
**Describe the bug**
Non-existing downvotes appear under the users' profile.

**To Reproduce**
1. Create a question
2. Check your user profile
3. See downvotes that have never been cast

**Expected behavior**
No downvotes if there is none.

**Screenshots**
![image](https://github.com/answerdev/answer/assets/4068/f7b43edc-b3e0-4929-91cb-dd3981774ece)
![image](https://github.com/answerdev/answer/assets/4068/1aca7cc2-4649-4d07-8d9b-7a206fcd352d)

**Platform (please complete the following information):**
Dockerized answer:1.1.0, SQLite database.

**Comment by fenbox** [comment]
fixed in v1.1.0
