### ISSUE TITLE
你们作为中国人，能用汉字么？

### ISSUE THREAD

**Issue by wulintang** [answerdev/answer#363]
好好地一个思否开源整得像个国外开源的，一个汉字都没有，原因是什么？你们思否背后是外资企业么？

**Comment by wulintang** [comment]
一个中国的项目一个中国的汉字都不用，这不是中国的项目走向国际化，而是压根没有把中国放在眼里。祖国培养大家不是为了把你们培养成崇洋媚外的一类人的。你们不是走向国际化，而是背离中国化。

**Comment by lbyxiaolizi** [comment]
《类人群星闪耀时》

**Comment by Aloento** [comment]
🤣👉
圣地巡礼

**Comment by 0w0-Yui** [comment]
🤣👉
圣地巡礼

**Comment by yanyao2333** [comment]
🤣👉
圣地巡礼

**Comment by Tim-Paik** [comment]
说实话，要是 VSCode 在 Wayland 下能支持中文输入法我绝对不会写英文注释，但是 chromium wayland 还不支持（
另外，github 本来也是英文网站，入乡随俗也是理所应当的

**Comment by g2nnyS** [comment]
首先这是GitHub，一个属于全世界程序员和开发者的网站，不是Gitee。一个国际网站，无论该项目的开发者的母语是什么，来自使用何种语言的国家，甚至是火星。开发者有在GitHub发布基于任何语言（这里指自然语言）的项目的自由和权利。这是一个面向全世界的开源项目而不是单单面向中国为中国人服务的一个东西。这也算崇洋媚外的话，那只能说你那可笑的民族自信就是民族自卑，你也根本不懂什么是民族自信和文化自信。如果你没有做好接纳其他文化和接受普世价值的准备的话，我建议你还是不要来到GitHub，国内有Gitee可以给你用。

**Comment by sider2vf** [comment]
Get out of Github, Nmslese! Go back to Gitee!
