### ISSUE TITLE
How to modify the email sending IP based on docker-compose?

### ISSUE THREAD

**Issue by alanwhy** [answerdev/answer#39]
![image](https://user-images.githubusercontent.com/34852024/198486309-35e0fc6f-eac4-4e18-b8e6-334aabc92a2c.png)

**Comment by husenlinwei** [comment]
`cd /answer/answer-data/data/conf`

Then, You can see the name is the `config.yaml` YAML file.

![image](https://user-images.githubusercontent.com/32996734/198500051-d68641c5-5fd2-4730-8bbb-5b4ef044d84e.png)

**Comment by alanwhy** [comment]
Very useful, thank you

**Comment by fenbox** [comment]
Now you can change in `Admin -> Settings -> SMTP`.
