### ISSUE TITLE
[Postgresql] A logged-in user viewing a question that has already been answered will get a 500 error when set Permalink to "/questions/D1D1" and "/questions/D1D1/post-title".

### ISSUE THREAD

**Issue by Liamn0244** [answerdev/answer#392]
**Describe the bug**
A logged-in user viewing a question that has already been answered will get a 500 error when set Permalink to "/questions/D1D1" and "/questions/D1D1/post-title". Special reminder that the database is postgresql.

**To Reproduce**
1. Login to Answer
2. Set Permalink to "/questions/D1D1" and "/questions/D1D1/post-title" (The other two permalink structures will not be a problem.)
3. Check the questions that have been answered on Answer homepage. 
4. Get 500 error.

**Expected behavior**
No 500 error.

**Screenshots**

<img width="529" alt="image" src="https://github.com/answerdev/answer/assets/135837370/7d1d430d-1a3d-4984-9a17-fdcc04d0ac4d">

<img width="1072" alt="20230607-201350@2x" src="https://github.com/answerdev/answer/assets/135837370/7bd2ae48-e3dd-47bf-8038-bd9e6416de10">

**Platform**
 - Device: Desktop
 - OS: macOS
 - Browser: Chrome
 - DB: Postgresql
 - Version: 1.1.0

**Comment by aichy126** [comment]
Thank you for your feedback. We are working on fixing the issue
https://github.com/answerdev/answer/commit/3092954e68d71860e8c47766fee8f37d383902e1
