### ISSUE TITLE
When the permalink structure is set to "/questions/D1D1" and "/questions/1001000000000000000000001", the links in the sitemap are still followed by "post-title".

### ISSUE THREAD

**Issue by Liamn0244** [answerdev/answer#393]
**Describe the bug**
When the permalink structure is set to "/questions/D1D1" and "/questions/1001000000000000000000001", the links in the sitemap are still followed by "post-title".

**To Reproduce**
1. Set the permalink structure to "/questions/D1D1" and "/questions/1001000000000000000000001".
2. Check the sitemap.
3. The links in the sitemap are still followed by "post-title".

**Expected behavior**
The links in the sitemap should correspond to the structure of the permalink links.

**Screenshots**
<img width="680" alt="image" src="https://github.com/answerdev/answer/assets/135837370/73d82259-756e-4c88-bc21-b7465ee0b5a7">

**Platform**
 - Device: Desktop
 - OS: macOS
 - Browser: chrome
 - Version: 1.1.0
 - DB: postgresql

**Comment by aichy126** [comment]
https://github.com/answerdev/answer/commit/3092954e68d71860e8c47766fee8f37d383902e1
Thank you for your feedback. We are working on fixing the issue

**Comment by Liamn0244** [comment]
I tested on the latest test branch and found that the problem was not fixed. Please check again.
Maybe I didn't describe it clearly enough.
The links in the sitemap should be consistent with the permalink structure set. If the permalink does not have a title at the end, then the link in the sitemap should also not end with a title.

**Comment by aichy126** [comment]
> I tested on the latest test branch and found that the problem was not fixed. Please check again. Maybe I didn't describe it clearly enough. The links in the sitemap should be consistent with the permalink structure set. If the permalink does not have a title at the end, then the link in the sitemap should also not end with a title.

Okay, I see what you mean. Let's fix it

**Comment by aichy126** [comment]
https://github.com/answerdev/answer/commit/cacf5e309f6f12656ede66a2cfa6233c82528794
We have fixed this issue here, which will be reflected in the 1.1.0 official release

**Comment by aichy126** [comment]
> Thanks. I have tested the main branch. The above problem has been solved.
> 
> I would like the URL link to the edited answer to be as consistent as possible with the permalink structure as well. Currently it looks like this: /posts/D1Q1/10020000000000016/edit I would like it to look like this: /posts/D1Q1/D2E1/edit
> 
> Share Answer link structure From: questions/D1Q1/10020000000000016?shareUserId=XXXX To: questions/D1Q1/D2E1?shareUserId=XXXX
> 
> There may be other links on the site that are not consistent with the permalink structure. So please change them all together.
> 
> This is a minor issue. It does not affect the use of the system. But I hope to improve it.

https://github.com/answerdev/answer/blob/0217125f6fc5d1f56f5280ec7feb1f655ad9f680/internal/service/answer_service.go#L563 
I fixed it here

**Comment by Liamn0244** [comment]
Thanks. I've tested it in the latest main branch(https://github.com/answerdev/answer/commit/204f5da7ef2ad62c912585ace4d4dd89941f91e6). The issue has been fixed.
