### ISSUE TITLE
How to create many users in bulk 

### ISSUE THREAD

**Issue by garg20garg** [answerdev/answer#417]
I want to know that how we create users in a bulk in answer.dev platform .

**Comment by garg20garg** [comment]
> Duplicate #184

Can You please explain step by step that how to create multiple users using admin panel .

**Comment by garg20garg** [comment]
> @garg20garg Sorry there is no feature to support bulk user creation yet.

can we create bulk user using development part ,if yes then can you please explain me about it.

**Comment by caixin107924** [comment]
能不能和LDAP集成，获取ldap上的用户登录系统？

**Comment by fenbox** [comment]
Released in [v1.1.2](https://github.com/answerdev/answer/releases/tag/v1.1.2).
