### ISSUE TITLE
Email notifications about new questions

### ISSUE THREAD

**Issue by radoslaw-warzocha** [answerdev/answer#419]
**Is your feature request related to a problem? Please describe.**
We are using Answer.dev as an internal Q&A platform, where internal teams answer questions coming from other developers in our organization. When people are asking a question, they can tag the corresponding team, and each member of said team follows the tags related to them. Unfortunately, we don't see a way to get notifications about a new question being posted with a specific tag, so we resort to checking Answer manually "every now and then". 

**Describe the solution you'd like**
We would love to have an option in the settings for "notify about new questions/new questions for the tags you follow", but even having an option to get notified on any new question coming in would be great.

**Describe alternatives you've considered**
For now, we're simply resorting to taking a look into our instance of Answer every now and then (and a Slack reminder to do so before clocking out).

**Comment by fenbox** [comment]
Released in [v1.1.2](https://github.com/answerdev/answer/releases/tag/v1.1.2). You can turn on email notification in `User -> Settings -> Notification`.
