### ISSUE TITLE
How to create many users in bulk using admin panel.

### ISSUE THREAD

**Issue by garg20garg** [answerdev/answer#420]
I have many users in our community so I want to insert all of them on a single click so can anyone help me to create multiple users using admin panel Please explain step by step .

**Comment by fenbox** [comment]
I'm sorry, but currently we do not have this feature. We are working on this.
Same as #184

**Comment by fenbox** [comment]
Released in [v1.1.2](https://github.com/answerdev/answer/releases/tag/v1.1.2).
