### ISSUE TITLE
send email dial fail

### ISSUE THREAD

**Issue by weizhii** [answerdev/answer#44]
/go/src/github.com/answerdev/answer/internal/service/export/email_service.go:108        send email to xxxxx@xxxxx.com failed: dial tcp 75.2.26.18:465: i/o timeout

can't connect 75.2.26.18:465

**Comment by halobug** [comment]
![image](https://user-images.githubusercontent.com/77707010/199385963-a4335d94-fac7-421f-9d2b-55d6d60239f9.png)
/internal/migrations/init.go
The mail channel should be configured independently

**Comment by halobug** [comment]
> 此电子邮件配置只是默认配置。您可以通过该界面配置 SMTP。 ![图片](https://user-images.githubusercontent.com/19712692/199387050-c0149d26-9e72-4069-94c5-f5cb3ac03fa7.png)

Thanks
