### ISSUE TITLE
First creation password too big for sign in UI

### ISSUE THREAD

**Issue by Nelinski** [answerdev/answer#476]
**Describe the bug**
When first creating an admin password, it lets you set what you want. However when trying to use that password to sign in, the UI caps your password at 32 characters meaning if you've set a long secure password you can't login. E.g. you lock yourself out from the start..

**To Reproduce**
1. Create a long password (e.g. 50 characters) during first set up
2. Try login to the UI

**Expected behavior**
You can set a long password and still login via the UI.

**Screenshots**
N/A

**Platform (please complete the following information):**
 - Device: Chromebook (albeit irrelevant)
 - OS: Docker/Unraid
 - Browser: Chrome
 - Version: 1.1.1

As a side note.. I can't login! So any suggestions either on how to reset the password without email or how the password is encrypted so I can update it in the DB would be appreciated.

**Comment by fenbox** [comment]
We will improve the usability of `type="password"`. Remove `maxlength` attr in HTML and use a "too long" message instead.

**Comment by carlqt** [comment]
Hi, looks like this is an easy fix for a beginner. Can I take it or it's still being discussed?

**Comment by fenbox** [comment]
@carlqt thank you for being willing to contribute to the fix, but we have already fixed it in the 1.1.3 branch. You are welcome to participate in fixing other issues.

**Comment by carlqt** [comment]
No worries, I will check other issues and contribute.

**Comment by fenbox** [comment]
fixed

> We will improve the usability of `type="password"`. Remove `maxlength` attr in HTML and use a "too long" message instead.

Fixed in v1.1.3
