### ISSUE TITLE
Can't @way users to invite users to answer?

### ISSUE THREAD

**Issue by huasio** [answerdev/answer#494]
![image](https://github.com/answerdev/answer/assets/23445537/e1467e99-c257-403c-93f8-081f956d7c5c)

@huasio it is invalid.

**Comment by sivdead** [comment]
@fenbox i would like to commit to this feature,do you have any flow design suggestion? or just find the symbok `@`, search the match user with username, then invite this user to answer?

**Comment by fenbox** [comment]
We hope that the answer area is answering questions.

It is not a good idea to make the invitation as part of the answer content, so the invitation function is specially made in the sidebar.

**Comment by fenbox** [comment]
> @fenbox i would like to commit to this feature,do you have any flow design suggestion? or just find the symbok `@`, search the match user with username, then invite this user to answer?

We hope that the answer area is answering questions, it's not a discussion.

It is not a good idea to make the invitation as part of the answer content, so the invitation function is specially made in the sidebar.

**Comment by sivdead** [comment]
> > @fenbox i would like to commit to this feature,do you have any flow design suggestion? or just find the symbok `@`, search the match user with username, then invite this user to answer?
> 
> We hope that the answer area is answering questions, it's not a discussion.
> 
> It is not a good idea to make the invitation as part of the answer content, so the invitation function is specially made in the sidebar.

ok
