### ISSUE TITLE
How can I delete other users from an administrator account?

### ISSUE THREAD

**Issue by alanwhy** [answerdev/answer#51]
How to delete on the page?

**Comment by alanwhy** [comment]
> ![image](https://user-images.githubusercontent.com/19712692/198944284-bd5853e8-c0f1-4016-86ed-d02e82363e14.png)
> 
> In admin page `users` tab. You can change user status to _deleted_, If the user email is already active.

Maybe there is something wrong with my version? I used Docker to deploy directly.

**Comment by husenlinwei** [comment]
Maybe you can see the HTTP response detail to help you.

**Comment by alanwhy** [comment]
Oh, I found a problem. If the current user is inactive, I can't delete it directly

**Comment by alanwhy** [comment]
> Maybe you can see the HTTP response detail to help you.

This really helped me, thank you
