### ISSUE TITLE
Errors about the installation

### ISSUE THREAD

**Issue by xioqing** [answerdev/answer#517]
v1.1.3
When I install with docker, I type http://localhost:9080 and it jumps me straight to the fourth part of the installation, the first three steps don't appear. 

log:
2023-09-07 01:21:54.236	ERROR	install/install_controller.go:177	read config failed stat /data/conf/config.yaml: no such file or directory

**Comment by shuashuai** [comment]
Thanks for the feedback, we will issue a patch immediately to fix this bug!

**Comment by shuashuai** [comment]
Now, the bug has been fixed, welcome to continue the experience.
