### ISSUE TITLE
Installing with docker How to connect to mysql

### ISSUE THREAD

**Issue by xioqing** [answerdev/answer#520]
Installing with docker How to connect to mysql,

log:
connection database failed: dial tcp 172.17.0.6:3306: connect: connection refused

**Comment by xioqing** [comment]
> Please make sure mysql address, port, username and password are correct. If you still can't connect, please provide more description.

If you could come up with a tutorial on how to connect to mysql, that would be great.
By the way, how does a binary installation start in the background.
Thank you for your time.

**Comment by sivdead** [comment]
> Installing with docker How to connect to mysql,
> 
> log: connection database failed: dial tcp 172.17.0.6:3306: connect: connection refused

i notice that your address 172.17.0.6 seems like Docker's default internal address, maybe you should create a network bind with mysql container and answer then use mysql:3306?

**Comment by aoeso8** [comment]
Database connection failed   
![企业微信截图_20230925092635](https://github.com/answerdev/answer/assets/106506163/548c37dd-8854-44ad-a6f3-da8983cc7007)

**Comment by aoeso8** [comment]
![企业微信截图_20230925093933](https://github.com/answerdev/answer/assets/106506163/519a4ec0-e447-4a69-8f9d-f20f72911e43)
不知道什么问题了，就是无法连接

**Comment by aoeso8** [comment]
我用的Alibaba Cloud Linux  3.2104 LTS 64位；![image](https://github.com/answerdev/answer/assets/106506163/3f59cfec-3906-4cad-97e0-cafd2b9c71e0)

**Comment by aoeso8** [comment]
sudo systemctl start mysqld
sudo systemctl enable mysqld  我们运行的mysqld 会不会和这个有关系呢？

**Comment by xioqing** [comment]
> sudo systemctl start mysqld sudo systemctl enable mysqld 我们运行的mysqld 会不会和这个有关系呢？

你用docker 安装一个mysql, 比如接口是3080, 127.0.0.1:3080 , 就行了
