### ISSUE TITLE
config.yaml fails to create on Windows

### ISSUE THREAD

**Issue by cdhunt** [answerdev/answer#536]
**Describe the bug**

**To Reproduce**
1. `./answer init -C C:\answer\data\`
2. Fill out the form
3. Click next

**Expected behavior**
It should create a populated `C:\answer\data\conf\config.yaml` file.

**Screenshots**
![image](https://github.com/answerdev/answer/assets/114173/c4404b6e-895e-4a3b-b5f9-5c81f2f1f811)

![image](https://github.com/answerdev/answer/assets/114173/f3d904ee-2186-467f-93aa-d3c404fefebb)

**Platform (please complete the following information):**
 - OS: Windows Server 2019

**Comment by cdhunt** [comment]
It looks like `http://localhost/install` is skipping straight to step 4 and [step 3](https://answer.dev/docs/installation#step-3-create-configuration-file) is never executed.

**Comment by cdhunt** [comment]
The first half of init doesn't execute. It's not that it can't create the file, it just never runs that method. Same for the DB. If I configured a DB connection it passes the connection test, but never creates the tables.

**Comment by EtBellatorLucis** [comment]
@LinkinStars Thank you very much for a fix and an amazing app!

**Comment by cdhunt** [comment]
Confirmed it is resolved.
