### ISSUE TITLE
Feature Request: Expand Upload Support to include additional File Formats (such as video)

### ISSUE THREAD

**Issue by grand-lotus-iroh** [answerdev/answer#538]
When composing a fresh post or posing a question, I encounter difficulty when attempting to drag and drop a compact 5 MB video file. I believe it would be highly beneficial to enable this feature and consider implementing upload size restrictions. It might be advantageous to introduce an option within the administrative settings under "Write" that allows users to toggle video upload support on or off. Additionally, it would be worthwhile to extend support for file formats like .webp, .wav, .heic, and more.

**Comment by fenbox** [comment]
Same as #211
