### ISSUE TITLE
The ability to receive real-time notifications on WeChat when users submit new questions to Answer, and the capability to easily submit answers on WeChat as well.

### ISSUE THREAD

**Issue by aoeso8** [answerdev/answer#551]
The ability to receive real-time notifications on WeChat when users submit new questions to Answer, and the capability to easily submit answers on WeChat as well.
example：
![image](https://github.com/answerdev/answer/assets/106506163/8fd21998-c3a1-43c5-828c-05536f00612a)

**Comment by aoeso8** [comment]
May I inquire whether it's possible to consider adding this feature? Alternatively, are there any other methods for achieving this?

**Comment by aoeso8** [comment]
Or, to take a step back, can you send an email notification when a new question is submitted?

**Comment by fenbox** [comment]
This is a very complex feature request. The message template rules for WeChat Official Accounts are complicated and the policies are constantly changing. We don't have the resources to handle these frequent changes.
