### ISSUE TITLE
能否设置开关支持登录后才可检索，内部使用的话要考虑信息安全防止信息泄露

### ISSUE THREAD

**Issue by fallencliff** [answerdev/answer#56]

**Comment by mingcheng** [comment]
感谢提供宝贵意见，这个功能我们会考虑在权限功能完善的情况后实现

**Comment by chinoll** [comment]
> 感谢提供宝贵意见，这个功能我们会考虑在权限功能完善的情况后实现

@mingcheng 可以添加邀请制注册吗？不开放注册功能，由后台添加账号

**Comment by mingcheng** [comment]
嗯呐，这个考虑会在后台增加个生成用户的功能

**Comment by joyqi** [comment]
Closed for non-English
