### ISSUE TITLE
feat : improve UX with custom scrollbar on website.

### ISSUE THREAD

**Issue by Sa24miksha** [answerdev/answer#567]
**Is your feature request related to a problem? Please describe.**
The website currently uses the default scrollbar, which can be enhanced for a better user experience.
This feature will eventually improve the UX of the website.
![WhatsApp Image 2023-10-12 at 2 51 29 PM](https://github.com/answerdev/answer/assets/100412207/dbe89e57-6710-479b-8730-133a353c25ec)

Requesting the implementation of a custom scrollbar in a visually appealing color to elevate the website's aesthetics.
According to my preference, the color #0834fc would suit well with the website's design.

I want to work on it, please assign it to me.

**Comment by Sa24miksha** [comment]
I have created the issue as i have already worked on it , please assign this to me

**Comment by fenbox** [comment]
@Sa24miksha If you want to change it, you can add customize CSS in the admin settings. There is no need to change the default browser style in Answer.

**Comment by Sa24miksha** [comment]
Please review it sir
