### ISSUE TITLE
Cannot delete tags because of existing posts

### ISSUE THREAD

**Issue by mortenbirkelund** [answerdev/answer#607]
**Describe the bug**
This may be more of a design decision than a bug, but it seems like the questions/answer is being soft-deleted, which means that you cannot delete the tags if they where ever used on a question/answer. If this is correct, then I think it must be a mistake, that softdelete have not been implemented for the tags aswell. 

In general i think it should be possible for an administrator to delete / modify tags created by the community. I suggest to be able to delete a tag, even if it is used on an active post. 

**To Reproduce**
1. Create a question with a new tag that havent been used before
2. Delete the question
3. Delete the new tag

**Expected behavior**
The tag should show as being used on 0 questions and you would be able to delete the tag

**Actual behavior**
The tag is shown as being used on 1 questions, and you cannot delete the tag. 

**Platform (please complete the following information):**
 - Device: [e.g. Desktop, Mobile]
 - OS: [e.g. macOS]

**Comment by mortenbirkelund** [comment]
This could be done as a part of a greater enhancement of the tags functionality, where it was made possible for an administrator to manage community created tags better. I think deleting, merging tags, creating synonyms and editing tags is highly relevant in order to moderate the tags created by various different users.

**Comment by fenbox** [comment]
@LinkinStars I can't reproduce, did you fixed in v1.2.0 already?

**Comment by mortenbirkelund** [comment]
@fenbox @LinkinStars I am using the Helm Chart. Current version is 1.0.7

Anything preventing this from being upgraded to 1.2.0?

**Comment by mortenbirkelund** [comment]
Forget that. I just checked, and the actual version is 1.2.0

It was just the chartVersion that wasnt updated. Also I think it is a mistake to set the images.tag to latest. Shouldn't that be the same version as the chart AppVersion?

**Comment by mortenbirkelund** [comment]
Spend some more time looking into it, and I couldnt figure out how to reproduce it. I had 2 tags that was shown as being related to question that didnt existsed anymore. 

I ended up just clearing them from the DB.
