### ISSUE TITLE
置顶功能或权重设计是否列入新的特性？

### ISSUE THREAD

**Issue by husenlinwei** [answerdev/answer#76]
是这样的，因为有一些公告需要置顶一段时间，但是当前完全是按照时间线排序？是否考虑加入权重值或其他设计方案？这个功能是否考虑在当前的新特性中？顺便问下能否公开你们在下一个版本优先开发的特性？

**Comment by ppchart** [comment]
Looking forward to revealing the Roadmap too

**Comment by husenlinwei** [comment]
@LinkinStars 是的，我看到了，感谢！

**Comment by husenlinwei** [comment]
> Looking forward to revealing the Roadmap too
https://github.com/orgs/answerdev/projects/1
