### ISSUE TITLE
管理员没有删除问题的权限？

### ISSUE THREAD

**Issue by chenfengrugao** [answerdev/answer#81]
管理员登录后，只看到”分享“和”Flag“，建议增加”删除“功能。

**Comment by notfresh** [comment]
我认为不能轻易删除问题，只能修改问题为其他人不可见，或者下线状态。

删除问题的话，需要认真确认

**Comment by chinoll** [comment]
> Thanks for the feedback, we are checking the problem.

可以给管理员增加编辑问题的权限吗？
