### ISSUE TITLE
建议：可以提供个 demo site

### ISSUE THREAD

**Issue by tvvocold** [answerdev/answer#9]
可以提供个 demo site 以便大家预览；）

**Comment by mingcheng** [comment]
感谢关注，其实我们目前已经在生产环境部署了一个副本，等到合适的时候（安全性、合规等等）会开放出来

**Comment by will-ww** [comment]
> 感谢关注，其实我们目前已经在生产环境部署了一个副本，等到合适的时候（安全性、合规等等）会开放出来

同样期待 Demo~

**Comment by geekymv** [comment]
个人部署的 demo 环境，欢迎访问 https://answer.npe4j.com
体验帐号 用户名 / 密码
`test01@test.com` / `test0101`

**Comment by will-ww** [comment]
> 个人部署的 demo 环境，欢迎访问 https://answer.npe4j.com 体验帐号 用户名 / 密码 `test01@test.com` / `test0101`

Cool, just tried, so good~

**Comment by LinuxSuRen** [comment]
没有默认的 SEO 信息吗？
![image](https://user-images.githubusercontent.com/1450685/197658651-efdb97d7-fd9c-48d6-8161-b0fd209e146d.png)

**Comment by fenbox** [comment]
> 没有默认的 SEO 信息吗？ ![image](https://user-images.githubusercontent.com/1450685/197658651-efdb97d7-fd9c-48d6-8161-b0fd209e146d.png)

SEO 相关正在开发中

**Comment by wolfidea** [comment]
没有中文版吗

**Comment by alanwhy** [comment]
> 

管理员登录后 可以修改默认的系统语言

**Comment by alanwhy** [comment]
> 没有中文版吗

管理员登录后，可以修改系统语言

**Comment by hanwenbo** [comment]
> > 个人部署的 demo 环境，欢迎访问 https://answer.npe4j.com 体验帐号 用户名 / 密码 `test01@test.com` / `test0101`
> 
> Cool, just tried, so good~

试了  运行速度慢 不知道是不是没压缩

**Comment by yujiaao** [comment]
布署一份，可以看看下面的用例

https://answer.bixuebihui.com/questions/10010000000000003/10020000000000006

如有语法高亮就好了

**Comment by mlsjla** [comment]
新鲜出炉， 默认语言也切换到中文了~~
https://bbs.zhanmishu.com/

**Comment by notfresh** [comment]
> 新鲜出炉， 默认语言也切换到中文了~~ https://bbs.zhanmishu.com/

没有吧，我咋看还是英文的！
![image](https://user-images.githubusercontent.com/12556509/201032650-5196f74c-deb9-4560-9995-7ffaef3fffd7.png)

**Comment by notfresh** [comment]
> 新鲜出炉， 默认语言也切换到中文了~~ https://bbs.zhanmishu.com/

@mlsjla

**Comment by notfresh** [comment]
> 个人部署的 demo 环境，欢迎访问 https://answer.npe4j.com 体验帐号 用户名 / 密码 `test01@test.com` / `test0101`

反馈个问题，这个网站没法更新头像

**Comment by joyqi** [comment]
Closed for non-English
