### ISSUE TITLE
Show/hide Q&A behind login

### ISSUE THREAD

**Issue by bennyzen** [answerdev/answer#93]
**Is your feature request related to a problem? Please describe.**
I'm wondering if there is the possibility to keep the questions and answers hidden behind the login. Right now everyone can go and read without signing in. 

**Describe the solution you'd like**
A switch to show/hide the 'content' behind a login would be very useful. This could be passed as env-var or be a toggle in the admin settings.

**Comment by fenbox** [comment]
Thanks for the feedback, the private site feature will be released next month.

**Comment by sunshineg** [comment]
> Thanks for the feedback, the private site feature will be released next month.

@fenbox looking forward to this feature ❤️

**Comment by quaintdev** [comment]
@fenbox  is it documented somewhere. I want my Q&A behind login.

**Comment by fenbox** [comment]
@quaintdev Turn on "Login required" in Admin->Settings->Login
