### ISSUE TITLE
建议增加放大图片和答案引用

### ISSUE THREAD

**Issue by chinoll** [answerdev/answer#94]
**Is your feature request related to a problem? Please describe.**
1. 像知乎那样点击放大图片，有些图片被缩放的比较小，难以查看
2. 可以引用其他问题的答案，像类似于A岛那种串引用

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by joyqi** [comment]
Hi, please write your issue in English. That way, more people can help you.
