### ISSUE TITLE
加载有点慢

### ISSUE THREAD

**Issue by chenfengrugao** [answerdev/answer#96]
main.xxx.js和main.xxx.css加载时间有点长。如果是第一次打开好像速度更慢。
![image](https://user-images.githubusercontent.com/32785798/204090813-92b22794-a0ab-4f77-8e6b-7fc30309e54f.png)
![image](https://user-images.githubusercontent.com/32785798/204090827-6211783b-bb2c-49d2-a576-e5d8e4cbcb25.png)

**Comment by robinv8** [comment]
This should be related to network bandwidth
