### ISSUE TITLE
网站在微信里打不开

### ISSUE THREAD

**Issue by chenfengrugao** [answerdev/answer#97]
在手机微信（android）里，网站首页可以打开，但问答的详情页打不开，如下图。可能是什么原因？

![1f3eecc039ab56a917291ee4315727b](https://user-images.githubusercontent.com/32785798/204091448-f10ab279-2e2e-4d64-8184-6cf4cd04ea8a.jpg)

**Comment by chenfengrugao** [comment]
找到问题了，是没有登录的原因。登录后就可以打开“问答”详细页面了，没有登录只能打开主页。

建议没有登录时，问答详细页面上给出提示，比如“请登录后查看”。或者有个option可以允许未登录浏览。谢谢！

**Comment by shuashuai** [comment]
Our details page does not block those who need to log in. It seems that the page rendering fails due to bad data. Can you provide a link to that page? Or open the console to provide detailed error information.


我们的详情页并没有屏蔽需要登录的人，看来是因为数据不好导致页面渲染失败。你能提供那个页面的链接吗？或者打开控制台提供详细的错误信息。

**Comment by shuashuai** [comment]
This issue has been fixed, you can pull the latest image to fix it.
