### ISSUE TITLE
对正在编辑中的问题或回答，是否可以有一个自动前端保存

### ISSUE THREAD

**Issue by hmlu** [answerdev/answer#99]
**Is your feature request related to a problem? Please describe.**
比如我正在编写一个问题，或者回答，不小心关闭了浏览器、刷新了浏览器或者死机，那编写了半天的内容就会丢失。

**Describe the solution you'd like**
是否可以做个定时自动保存到用户浏览器的 LocalStorage 中，这样即使是不小心了刷新页面、或死机等异常情况不会导致我编写的内容丢失。

**Comment by joyqi** [comment]
Hi, please write your issue in English. That way, more people can help you.
